

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import ReduxProvider from "./reduxWrapper/redux-provider";
import { Toaster } from "react-hot-toast";


const poppins = Poppins({
  subsets: ["latin"],
  weight: [ "100" , "200" , "300" , "400" , "500" , "600" , "700" , "800" , "900" ]
});

export const metadata: Metadata = {
  title: "Carefood",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  
      <body className={`${poppins.className} bg-[#F6F6F6] `}>
      <ReduxProvider>
        <Navbar />
        {children}
        <Toaster position="bottom-right" />
        </ReduxProvider></body>
    
    </html>
  );
}
